# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM registry.cn-hangzhou.aliyuncs.com/youchainhq/xgo:1.12.x

LABEL MAINTAINER Péter Szilágyi <peterke@gmail.com>
